Only render every n episode
ericyangyu/PPO-for-Beginners pull request #3
Opened 2021-01-01 15:29 UTC by clemens-tolboom

It would be nice to show only some renderings

2021-01-10 21:20 UTC, ericyangyu requested changes

2021-01-11 11:23 UTC, clemens-tolboom commented on ppo.py
> +				if self.render and (self.logger['t_so_far'] + len(batch_lens)) % self.render_every == 0:
IIRC there was a non equal sizes thing ... will come back on it after my Godot racing track is in *Gym* mode.

2021-01-11 22:10 UTC, ericyangyu commented on ppo.py
> +				if self.render and (self.logger['t_so_far'] + len(batch_lens)) % self.render_every == 0:
Sounds good! I'll keep this pr open in the meantime.

2021-02-08 13:09 UTC, clemens-tolboom commented on ppo.py
> +				if self.render and (self.logger['i_so_far'] % self.render_every_i == 0) and len(batch_lens) == 0:
I'm not sure what `and len(batch_lens) == 0` does but added it anyway.

2021-02-08 13:09 UTC, clemens-tolboom commented
I set `render === True` as we are running Gym stuff ... hope you agree :-O

2021-03-03 09:41 UTC, ericyangyu commented on ppo.py
> +				if self.render and (self.logger['i_so_far'] % self.render_every_i == 0) and len(batch_lens) == 0:
I added `len(batch_lens) == 0` since each iteration rollout collects data from multiple episodes. I figured it's better to just render 1 of those episodes in i-th iteration instead of all episodes in i-th iteration.

2021-03-03 09:42 UTC, ericyangyu approved these changes
Looking great! Thank you for your contributions Clemens.

2021-03-03 09:42 UTC, merged

2021-03-03 09:54 UTC, clemens-tolboom commented
Thanks for the articles and this repo :-)